
#s Aliases
alias update_aliases='if [ -f ~/Development/scripts/Bash/alias/bash_aliases ]; then cp ~/Development/scripts/Bash/alias/bash_aliases ~/.bash_aliases_ && rm ~/.bash_aliases && mv ~/.bash_aliases_ ~/.bash_aliases fi'
alias showsshconfig='cat ~/.ssh/config'
alias pcup='sudo dnf update -y'

#P Aliases
alias dev='cd /home/$USER/Development'
alias showalias='cat ~/.bash_aliases'
alias opendev='code ~/Development/'
alias start_gh_dev='opendev && gnome-terminal -- bash -c "docker start gh_api && docker attach gh_api" '
alias accdb='sqlite3 /run/media/$USER/Yellowtail/0001_ANDY/Accounts/newACCS.db'
alias activatecliapp="podman start gh_api && podman attach gh_api"
alias sqliteb='~/.Installs/DB_Browser_for_SQLite-v3.12.2-x86_64.AppImage &'


#W Aliases
alias activatespot='source /home/$USER/Development/2_PyVenvs/spot-pp-stq/bin/activate'
alias activatepp='gnome-terminal -- bash -c "docker start pp_ngitws && docker attach pp_ngitws"'
alias gocws='cd /home/$USER/Development/0_Workaton/curl_catalog/'
alias gosapi='cd /home/$USER/Development/Spot/1_SPOT_API/'
alias openspot='code /home/$USER/Development/Spot/'
